//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja_deweloperska_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class firma_deweloperska_2Entities : DbContext
    {
        public firma_deweloperska_2Entities()
            : base("name=firma_deweloperska_2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DEADLINE> DEADLINEs { get; set; }
        public DbSet<PRACOWNICY> PRACOWNICies { get; set; }
        public DbSet<PRIORYTETY> PRIORYTETies { get; set; }
        public DbSet<PRZEZNACZENIE> PRZEZNACZENIEs { get; set; }
        public DbSet<SPRZET> SPRZETs { get; set; }
        public DbSet<UMOWY> UMOWies { get; set; }
        public DbSet<WYDATKI> WYDATKIs { get; set; }
        public DbSet<ZESPOLY> ZESPOLies { get; set; }
        public DbSet<ZLECENIA> ZLECENIAs { get; set; }
        public DbSet<ZYSKI> ZYSKIs { get; set; }
    }
}
