//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja_deweloperska_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACOWNICY
    {
        public PRACOWNICY()
        {
            this.UMOWies = new HashSet<UMOWY>();
            this.WYDATKIs = new HashSet<WYDATKI>();
            this.ZESPOLies = new HashSet<ZESPOLY>();
        }
    
        public decimal PRAC_ID { get; set; }
        public string PRAC_IMIE { get; set; }
        public string PRAC_NAZWISKO { get; set; }
        public string PRAC_PESEL { get; set; }
        public string PRAC_ADRES { get; set; }
        public string PRAC_EMAIL { get; set; }
        public string PRAC_TELEFON { get; set; }
        public string PRAC_STANOWSKO { get; set; }
    
        public virtual ICollection<UMOWY> UMOWies { get; set; }
        public virtual ICollection<WYDATKI> WYDATKIs { get; set; }
        public virtual ICollection<ZESPOLY> ZESPOLies { get; set; }
    }
}
