//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja_deweloperska_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRZEPLYWGOTOWKI
    {
        public decimal PRZEP_ID { get; set; }
        public Nullable<decimal> ZLEC_ID { get; set; }
        public decimal PRZEP_KWOTA { get; set; }
        public string PRZEP_OPIS { get; set; }
    
        public virtual ZLECENIA ZLECENIA { get; set; }
    }
}
