//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja_deweloperska_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPRZET
    {
        public decimal SPRZET_ID { get; set; }
        public Nullable<decimal> ZESP_ID { get; set; }
        public string SRZET_NAZWA { get; set; }
        public int SPRZET_ILOSC { get; set; }
    
        public virtual ZESPOLY ZESPOLY { get; set; }
    }
}
