//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja_deweloperska_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZESPOLY
    {
        public ZESPOLY()
        {
            this.PRACOWNICies = new HashSet<PRACOWNICY>();
            this.SPRZETs = new HashSet<SPRZET>();
            this.ZLECENIAs = new HashSet<ZLECENIA>();
        }
    
        public decimal ZESP_ID { get; set; }
        public string ZESP_NAZWA { get; set; }
    
        public virtual ICollection<PRACOWNICY> PRACOWNICies { get; set; }
        public virtual ICollection<SPRZET> SPRZETs { get; set; }
        public virtual ICollection<ZLECENIA> ZLECENIAs { get; set; }
    }
}
