//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja_deweloperska_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZESPOLY
    {
        public ZESPOLY()
        {
            this.ZLECENIAs = new HashSet<ZLECENIA>();
        }
    
        public decimal ZESP_ID { get; set; }
        public Nullable<decimal> PRAC_ID { get; set; }
        public Nullable<decimal> SPRZET_ID { get; set; }
    
        public virtual PRACOWNICY PRACOWNICY { get; set; }
        public virtual SPRZET SPRZET { get; set; }
        public virtual ICollection<ZLECENIA> ZLECENIAs { get; set; }
    }
}
