//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja_deweloperska_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZLECENIA
    {
        public ZLECENIA()
        {
            this.PRZEPLYWGOTOWKIs = new HashSet<PRZEPLYWGOTOWKI>();
        }
    
        public decimal ZLEC_ID { get; set; }
        public Nullable<decimal> ZESP_ID { get; set; }
        public Nullable<decimal> PRIO_ID { get; set; }
        public System.DateTime ZLEC_ROZPOCZECIE { get; set; }
        public bool ZLEC_ZAKONCZONO { get; set; }
        public string ZLEC_OPIS { get; set; }
    
        public virtual PRIORYTETY PRIORYTETY { get; set; }
        public virtual ICollection<PRZEPLYWGOTOWKI> PRZEPLYWGOTOWKIs { get; set; }
        public virtual ZESPOLY ZESPOLY { get; set; }
    }
}
